Data and sentiments analysis
abrakadabror/Tripadvisor_sentiment pull request #1
Opened 2023-06-18 11:00 UTC by abrakadabror

2023-06-18 11:03 UTC, PiotrSkoupy requested changes

2023-06-18 11:03 UTC, PiotrSkoupy commented on main.py
> +    # print(reviews_on_single_page)
usuń komentarze

2023-06-18 11:03 UTC, PiotrSkoupy commented on main.py
> +# uczenie maczynowe NLP  natural langiuage processing i polega na przetwarzaniu jezyka aby znaleźc w nim sens
Usuń rzeczy z #

2023-06-19 19:14 UTC, abrakadabror commented on main.py
> +# uczenie maczynowe NLP  natural langiuage processing i polega na przetwarzaniu jezyka aby znaleźc w nim sens
Usunięto rzeczy z # w lini 76

2023-06-19 19:14 UTC, abrakadabror commented on main.py
> +    # print(reviews_on_single_page)
usunięto komentarz  w lini 45

2023-06-19 19:38 UTC, merged